# Generated by Django 2.0.5 on 2018-05-25 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('poster', models.ImageField(blank=True, upload_to='uploads/%Y/%m', verbose_name='海报图')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('is_top', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='NO', max_length=1, verbose_name='是否置顶')),
                ('is_publish', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='YES', max_length=1, verbose_name='是否发布')),
                ('is_reprint', models.CharField(choices=[('1', 'YES'), ('0', 'NO')], default='NO', max_length=1, verbose_name='是否转载')),
                ('comment_counts', models.IntegerField(default=0, verbose_name='评论数量')),
                ('read_counts', models.IntegerField(default=0, verbose_name='阅读数量')),
                ('fav_counts', models.IntegerField(default=0, verbose_name='喜欢数量')),
            ],
            options={
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=15)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('content', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='发表日期')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webblog.Article')),
                ('p_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webblog.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webblog.Category', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='webblog.Tag', verbose_name='标签'),
        ),
    ]
