# Generated by Django 2.0.5 on 2018-05-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fav_counts',
            field=models.IntegerField(default=0, verbose_name='喜欢数量'),
        ),
        migrations.AddField(
            model_name='article',
            name='read_counts',
            field=models.IntegerField(default=0, verbose_name='阅读数量'),
        ),
    ]
